{
  imports = [
    ./adsb.nix
    ./backups.nix
    ./bambuddy.nix
    ./bin-compat.nix
    ./btrfs.nix
    ./dcs-server.nix
    ./debug-probes.nix
    ./desktop.nix
    ./dns.nix
    ./flatpak.nix
    ./framework.nix
    ./fwupd.nix
    ./gaming.nix
    ./home-assistant.nix
    ./is-laptop.nix
    ./matter.nix
    ./mqtt.nix
    ./network-drives.nix
    ./nix-gc.nix
    ./secure-boot.nix
    ./snapper.nix
    ./tpm-luks.nix
    ./traefik.nix
    ./users.nix
    ./vr.nix
    ./wifi.nix
    ./zigbee.nix
    ./zwave.nix
  ];
}
