# Home Assistant automation for reliant: presence-driven room lighting.
#
# Turns a room's lights on while its presence sensor detects someone, and off
# five minutes after presence clears. One desired-state automation per room,
# generated by mkPresenceLighting from just the room's two entities — add
# another room by dropping an entry into `rooms` with that room's presence
# sensor and lights; nothing else changes.
#
# Restart-resilient in the same spirit as outside-lights.nix: alongside the
# presence on/off edges, a `homeassistant` start trigger re-derives the desired
# state (lights on iff presence is currently detected) so a reboot or config
# reload restores the correct state rather than waiting for the next presence
# edge. The five-minute linger lives in the off-trigger's `for`; it is
# intentionally not persisted across a restart — after a reboot the lights
# simply track current presence. For a room with a `door` sensor, `linger` is
# the max/fallback wait (used when the door stays open) and the shorter
# `doorClosedLinger` is the wait once the door has also closed — see below.
#
# `presence` just needs to be a binary_sensor.* that reports on/off — the
# automation itself doesn't care whether "off" means the room emptied
# (continuous occupancy sensing) or the sensor's own hardware clear timer
# expired (a classic motion sensor). Two kinds are in use:
#
# - Aqara FP1e mmWave sensors bridged in through an Aqara M2 hub over Matter
#   (custom.matter + the "matter" extraComponent, both in
#   hosts/reliant/configuration.nix). These hold binary_sensor "on" for as
#   long as someone is actually present, and clear to "off" almost
#   immediately once the room is empty — `linger` is then effectively the
#   whole "stay lit after leaving" delay.
# - Zigbee PIR motion sensors via Zigbee2MQTT (mqtt extraComponent). These
#   clear to "off" only after their own internal occupancy timeout (commonly
#   60-120s, configurable per device in Zigbee2MQTT), so the real "dark
#   delay" after the last actual motion is that sensor timeout *plus*
#   `linger` — pick a shorter `linger` for these than for a continuous
#   presence sensor if stacking the two would overshoot.
#
# A room's lights may be a light.* or a switch.* entity; the on/off service
# is derived from the entity's own domain (light.turn_on / switch.turn_on /
# ...), so either wiring works unchanged.
#
# Geoff's Office uses its real, commissioned FP1e entity IDs (originally
# copied from hosts/defiant/home-assistant/presence-lighting.nix). The
# Utility Room entry uses its real, commissioned Zigbee PIR motion sensor and
# switch.
#
# The Utility Room also has a Parasoll door/window contact sensor on the
# door (binary_sensor.utility_room_parasoll_contact, device_class "door":
# "on" = open, "off" = closed) wired in via the optional `door` parameter.
# When set, opening the door is an extra "instant on" trigger — useful
# because the motion sensor's own occupancy timeout means the first second
# or two of someone stepping in isn't necessarily covered yet. The door does
# NOT gate the off side the same way it gates the on side: it's an additional
# way to turn lights on, not a second presence source, so motion alone still
# decides on. For off, once `door` is set, the door does shorten the wait:
# presence clearing and the door being (or becoming) closed together for
# `doorClosedLinger` turns lights off quickly (person left and shut the door
# behind them), while the plain `presence -> off, for = linger` trigger
# remains as the max/fallback wait that fires regardless of door state, so a
# door propped open doesn't keep the lights on forever.
#
# Declared under the "automation manual" key (not bare "automation") so these
# coexist with any UI-created automations, matching
# services.home-assistant.configWritable = true. NixOS merges this list with the
# "automation manual" lists in the sibling files under this directory (see
# default.nix).
{lib, ...}: {
  services.home-assistant.config."automation manual" = let
    # Build one restart-resilient desired-state automation for a room from just
    # its presence sensor and lights entity. `slug` is the entity-safe id stem;
    # `linger` is how long the lights stay on after presence clears. The turn
    # on/off service is taken from the lights entity's domain, so `lights` may
    # be a light.* or switch.* (or any domain exposing turn_on/turn_off).
    mkPresenceLighting = {
      room,
      slug,
      presence,
      lights,
      door ? null,
      linger ? "00:05:00",
      doorClosedLinger ? "00:01:00",
    }: let
      domain = builtins.head (lib.splitString "." lights);
      onCondition =
        if door == null
        then {
          condition = "state";
          entity_id = presence;
          state = "on";
        }
        else {
          condition = "or";
          conditions = [
            {
              condition = "state";
              entity_id = presence;
              state = "on";
            }
            {
              condition = "state";
              entity_id = door;
              state = "on";
            }
          ];
        };
    in {
      id = "presence_lighting_${slug}";
      alias = "${room} lights follow presence";
      description = "Turn on ${room}'s lights while presence is detected${lib.optionalString (door != null) " or the door is open"} and off ${
        if door == null
        then "${linger} after presence clears"
        else "${doorClosedLinger} after presence clears and the door is closed, or after ${linger} regardless of door state"
      }. Re-evaluated on presence edges${lib.optionalString (door != null) ", the door opening or closing,"} and on Home Assistant startup.";
      mode = "single";
      trigger =
        [
          # Presence detected -> lights should be on.
          {
            platform = "state";
            entity_id = presence;
            to = "on";
          }
          # Presence has been clear for the full linger window -> lights off.
          # For a room with `door` set, this is the max/fallback wait that
          # fires even if the door stays open; the shorter door-aware trigger
          # below usually fires first.
          {
            platform = "state";
            entity_id = presence;
            to = "off";
            for = linger;
          }
          # Restore the correct state after a reboot or config reload.
          {
            platform = "homeassistant";
            event = "start";
          }
        ]
        ++ lib.optional (door != null) {
          # Door opened -> instant on, independent of motion. Does not gate
          # the off side; see the header comment.
          platform = "state";
          entity_id = door;
          to = "on";
        }
        ++ lib.optional (door != null) {
          # Presence clear and the door (also) closed, continuously, for the
          # shorter doorClosedLinger -> lights off sooner than the plain
          # linger fallback above (person left and shut the door).
          platform = "template";
          value_template = "{{ is_state('${presence}', 'off') and is_state('${door}', 'off') }}";
          for = doorClosedLinger;
        };
      action = [
        {
          choose = [
            {
              # Presence currently detected (or the door is currently open,
              # when `door` is set) -> lights on.
              conditions = [onCondition];
              sequence = [
                {
                  service = "${domain}.turn_on";
                  target.entity_id = lights;
                }
              ];
            }
          ];
          # No presence (cleared past the linger or the shorter
          # doorClosedLinger, or startup with the room empty and door
          # closed) -> lights off.
          default = [
            {
              service = "${domain}.turn_off";
              target.entity_id = lights;
            }
          ];
        }
      ];
    };
  in
    map mkPresenceLighting [
      {
        room = "Geoff's Office";
        slug = "geoffs_office";
        presence = "binary_sensor.geoff_s_office_presence_occupancy";
        lights = "light.geoff_s_office_lights";
      }
      {
        room = "Utility Room";
        slug = "utility_room";
        presence = "binary_sensor.motion_sensor_utility_room_occupancy";
        lights = "switch.utility_room";
        door = "binary_sensor.utility_room_parasoll_contact";
        doorClosedLinger = "00:01:00";
      }
    ];
}
