# Home Assistant automation for reliant: presence-driven room lighting.
#
# Turns a room's lights on while its presence sensor detects someone, and off
# five minutes after presence clears. One desired-state automation per room,
# generated by mkPresenceLighting from just the room's two entities — add
# another room by dropping an entry into `rooms` with that room's presence
# sensor and lights; nothing else changes.
#
# Restart-resilient in the same spirit as outside-lights.nix: alongside the
# presence on/off edges, a `homeassistant` start trigger re-derives the desired
# state (lights on iff presence is currently detected) so a reboot or config
# reload restores the correct state rather than waiting for the next presence
# edge. The five-minute linger lives in the off-trigger's `for`; it is
# intentionally not persisted across a restart — after a reboot the lights
# simply track current presence.
#
# The presence sensors are Aqara FP1e mmWave sensors bridged into Home Assistant
# through an Aqara M2 hub over Matter (custom.matter + the "matter"
# extraComponent, both in hosts/reliant/configuration.nix). HA exposes the FP1e
# occupancy as a binary_sensor.* (on = detected). A room's lights may be a
# light.* or a switch.* entity; the on/off service is derived from the entity's
# own domain (light.turn_on / switch.turn_on / ...), so either wiring works
# unchanged.
#
# Geoff's Office uses its real, commissioned entity IDs. For a room added before
# its FP1e is commissioned, the real occupancy entity ID isn't known until the
# M2 hub is paired and the sensor appears in Home Assistant, so use a placeholder
# `presence` and update it after commissioning. Copied from
# hosts/defiant/home-assistant/presence-lighting.nix — re-verify these entity
# IDs against the running instance on this host once activated.
#
# Declared under the "automation manual" key (not bare "automation") so these
# coexist with any UI-created automations, matching
# services.home-assistant.configWritable = true. NixOS merges this list with the
# "automation manual" lists in the sibling files under this directory (see
# default.nix).
{lib, ...}: {
  services.home-assistant.config."automation manual" = let
    # Build one restart-resilient desired-state automation for a room from just
    # its presence sensor and lights entity. `slug` is the entity-safe id stem;
    # `linger` is how long the lights stay on after presence clears. The turn
    # on/off service is taken from the lights entity's domain, so `lights` may
    # be a light.* or switch.* (or any domain exposing turn_on/turn_off).
    mkPresenceLighting = {
      room,
      slug,
      presence,
      lights,
      linger ? "00:05:00",
    }: let
      domain = builtins.head (lib.splitString "." lights);
    in {
      id = "presence_lighting_${slug}";
      alias = "${room} lights follow presence";
      description = "Turn on ${room}'s lights while presence is detected and off ${linger} after it clears. Re-evaluated on presence edges and on Home Assistant startup.";
      mode = "single";
      trigger = [
        # Presence detected -> lights should be on.
        {
          platform = "state";
          entity_id = presence;
          to = "on";
        }
        # Presence has been clear for the full linger window -> lights off.
        {
          platform = "state";
          entity_id = presence;
          to = "off";
          for = linger;
        }
        # Restore the correct state after a reboot or config reload.
        {
          platform = "homeassistant";
          event = "start";
        }
      ];
      action = [
        {
          choose = [
            {
              # Presence currently detected -> lights on.
              conditions = [
                {
                  condition = "state";
                  entity_id = presence;
                  state = "on";
                }
              ];
              sequence = [
                {
                  service = "${domain}.turn_on";
                  target.entity_id = lights;
                }
              ];
            }
          ];
          # No presence (cleared past the linger, or startup with the room
          # empty) -> lights off.
          default = [
            {
              service = "${domain}.turn_off";
              target.entity_id = lights;
            }
          ];
        }
      ];
    };
  in
    map mkPresenceLighting [
      {
        room = "Geoff's Office";
        slug = "geoffs_office";
        presence = "binary_sensor.geoff_s_office_presence_occupancy";
        lights = "light.geoff_s_office_lights";
      }
    ];
}
