_: let
  nas = import ../../lib/nas.nix;
  thomasga = import ../../users/thomasga/account.nix;
in {
  imports = [
    ./secrets.nix
    ../../roles/common
    ../../roles/dev

    ../../modules
    # NOT: roles/desktop — no display server
  ];

  wsl = {
    enable = true;
    defaultUser = "thomasga";
    startMenuLaunchers = true;
  };

  custom = {
    users.thomasga =
      thomasga
      // {
        groups = ["wheel" "networkmanager"];
        avatar = null;
      };

    backups = {
      enable = true;

      nas = {
        credentialsFile = "/run/agenix/thomasga/nas-smb-credentials";
        # Addressed by IP rather than by name, unlike enterprise-d and defiant.
        # Those two resolve nas.host through a networking.hosts entry, which
        # writes /etc/hosts — and under WSL that file is regenerated by Windows
        # unless wsl.conf opts out, so the name is not known to resolve here.
        # The fact still comes from lib/nas.nix either way, which is the point:
        # move the NAS and every host follows.
        host = nas.ip;
        share = nas.shares.backups;
      };

      users.thomasga.enable = true;
    };
  };

  services.openssh = {
    enable = true;
    settings = {
      KbdInteractiveAuthentication = false;
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  networking.hostName = "holodeck-01";
  system.stateVersion = "25.11";
}
